print("hola")
print("hola")
print("hola")
print("hola")
print("hola")
print("hola")
print("hola")
print("hola")
print("hola")
print("hola")
print("hola")
print("hola")
print("hola")
print("nueva linea")

print("AAAAAAAAAAAAAAAAAAAAAAA")
print("AAAAAAAAAAAAAAAAAAAAAAA")
print("AAAAAAAAAAAAAAAAAAAAAAA")
